export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const DELETE_POST_SUCCESS= 'DELETE_POST_SUCCESS'

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_ERROR = 'ADD_POST_ERROR'

export const SET_NULL_ADD_POST_ERROR = "SET_NULL_ADD_POST_ERROR";

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'