export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_ERROR = 'FETCH_REVIEWS_ERROR'

export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
